apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectId }}-filebrowser
  labels:
    app: {{ .Values.projectId }}-filebrowser
spec:
  clusterIP: None
  ports:
    - port: 9696
      targetPort: 9696
      protocol: TCP
      name: filebrowser
  selector:
    app: {{ .Values.projectId }}-filebrowser
