apiVersion: v2
type: application
name: kdl-server
description: A Helm chart to deploy KDL server
version: 6.0.2
appVersion: 1.38.0
sources:
  - https://github.com/konstellation-io/kdl-server
home: https://www.konstellation.io
maintainers:
  - name: ialejandro
    email: ivan.alejandro@intelygenz.com
keywords:
  - ia
  - kdl
  - kdl-server
  - konstellation
  - kubernetes
  - machine learning
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
