apiVersion: v2
type: application
name: kdl-server
description: A Helm chart to deploy KDL server
version: 6.2.2
appVersion: 1.40.1
sources:
  - https://github.com/konstellation-io/kdl-server
home: https://www.konstellation.io
maintainers:
  - name: ialejandro
    email: ivan.alejandro@intelygenz.com
  - name: alpiquero
    email: angelluis.piquero@intelygenz.com
  - name: danielchg
    email: daniel.chavero@intelygenz.com
keywords:
  - ai
  - kdl
  - kdl-server
  - konstellation
  - kubernetes
  - machine learning
dependencies:
  - name: konstellation-base
    alias: keycloak
    version: "1.1.2"
    repository: oci://ghcr.io/konstellation-io/helm-charts
    condition: keycloak.enabled
  - name: minio
    version: "3.2.0"
    repository: https://charts.min.io
    condition: minio.enabled
  - name: mongodb
    version: "16.2.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: oauth2-proxy
    alias: oauth2proxy
    version: "7.7.28"
    repository: oci://ghcr.io/oauth2-proxy/charts
    condition: oauth2proxy.enabled
  - name: postgresql
    version: "15.5.38"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
