# See https://github.com/helm/chart-testing#configuration
chart-dirs: charts
chart-repos:
- minio=https://charts.min.io/
check-version-increment: true
debug: false
remote: origin
target-branch: main
upgrade: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
