apiVersion: v1
kind: ConfigMap
metadata:
  name: kdl-server-oauth2-proxy
data:
  oauth2_proxy.cfg: |+
    provider="gitea"
    cookie_secret="_csrf"
    login_url="{{ printf "%s://gitea.%s/login/oauth/authorize" ( include "protocol" . ) .Values.domain }}"
    redeem_url="{{ printf "%s://gitea.%s/login/oauth/access_token" ( include "protocol" . ) .Values.domain }}"
    profile_url="{{ printf "%s://gitea.%s/api/v1/user" ( include "protocol" . ) .Values.domain }}"
    redirect_url="{{ printf "%s://app.%s/oauth2/callback" ( include "protocol" . ) .Values.domain }}"
    cookie_secure={{ ternary "true" "false" .Values.tls.enabled }}
    cookie_samesite="none"
    ssl_insecure_skip_verify=true
    ssl_upstream_insecure_skip_verify=true
