apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kdl-server.server.name" . }}-user-tools-template
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
  labels:
    {{- include "kdl-server.kdlServerLabels" . | nindent 4 }}
data:
  template: |
    {{- with .Values.userToolsOperator.templateCustomResource }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
