apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kdl-server.server.name" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
  labels:
    {{- include "kdl-server.kdlServerLabels" . | nindent 4 }}
data:
  ##
  # KDL APP configuration
  KDL_SERVER_PORT: {{ .Values.env.KDL_SERVER_PORT | default (int .Values.service.targetPort | default .Values.service.port) | quote }}
  BASE_DOMAIN_NAME: {{ .Values.global.domain }}
  SHARED_VOLUME: {{ .Values.sharedVolume.name }}

  TLS_ENABLED: "{{ .Values.global.ingress.tls.enabled }}"

  config.json: |+
    {
      "DESCRIPTION_MIN_WORDS": {{ default "50" .Values.knowledgeGalaxy.config.descriptionMinWords }}
      "KG_SERVER_URL": "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/kg",
      "KNOWLEDGE_GALAXY_ENABLED": {{ .Values.knowledgeGalaxy.enabled }},
      "RELEASE_VERSION": "{{ .Chart.AppVersion }}",
      "SERVER_NAME": "{{ .Values.global.serverName }}",
      "SERVER_URL": "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}",
    }

  ##
  # KDL URL Setup
  PROJECT_FILEBROWSER_URL: "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/filebrowser/PROJECT_ID/"
  PROJECT_MLFLOW_URL: "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/mlflow/PROJECT_ID/"
  USER_TOOLS_VSCODE_URL: "{{ include "http.protocol" . }}://USERNAME-code.{{ .Values.global.domain }}/?folder=/home/coder/repos/REPO_FOLDER"

  ##
  # Knowledge Galaxy
  KNOWLEDGE_GALAXY_URL: "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/kg/projects/PROJECT_ID/"
  KNOWLEDGE_GALAXY_ENABLED: "{{ .Values.knowledgeGalaxy.enabled }}"

  ##
  # User Tools Operator
  VSCODE_IMG_REPO: "{{ .Values.userToolsOperator.vscode.image.repository }}"
  VSCODE_IMG_TAG: "{{ .Values.userToolsOperator.vscode.image.tag }}"
  VSCODE_IMG_PULLPOLICY: "{{ .Values.userToolsOperator.vscode.image.pullPolicy }}"

  REPO_CLONER_IMG_REPO: "{{ .Values.userToolsOperator.repoCloner.image.repository }}"
  REPO_CLONER_IMG_TAG: "{{ .Values.userToolsOperator.repoCloner.image.tag }}"
  REPO_CLONER_IMG_PULLPOLICY: "{{ .Values.userToolsOperator.repoCloner.image.pullPolicy }}"

  USER_TOOLS_VSCODE_RUNTIME_IMG_REPO: "{{ .Values.userToolsOperator.vscodeRuntime.image.repository }}"
  USER_TOOLS_VSCODE_RUNTIME_IMG_TAG: "{{ .Values.userToolsOperator.vscodeRuntime.image.tag }}"
  USER_TOOLS_VSCODE_RUNTIME_IMG_PULLPOLICY: "{{ .Values.userToolsOperator.vscodeRuntime.image.pullPolicy }}"

  USER_TOOLS_KUBECONFIG_DOWNLOAD_ENABLED: "{{ .Values.userToolsOperator.kubeconfig.enabled }}"
  USER_TOOLS_KUBECONFIG_EXTERNAL_SERVER_URL: "{{ .Values.userToolsOperator.kubeconfig.externalServerUrl }}"

  USER_TOOLS_STORAGE_SIZE: {{ .Values.userToolsOperator.storage.size }}
  USER_TOOLS_STORAGE_CLASSNAME: {{ .Values.userToolsOperator.storage.storageClassName }}
  {{- if .Values.userToolsOperator.ingress.className }}
  USER_TOOLS_INGRESS_CLASS_NAME: {{ .Values.userToolsOperator.ingress.className }}
  {{- end }}
  # Base64 encoded string of the user-tools ingress annotations
  USER_TOOLS_ENCODED_INGRESS_ANNOTATIONS: |+
    {{- toYaml .Values.userToolsOperator.ingress.annotations | b64enc | nindent 4 }}
  {{- if and .Values.global.ingress.tls.enabled (or (not (kindIs "invalid" .Values.userToolsOperator.ingress.tls.secretName )) (not (kindIs "invalid" .Values.global.ingress.tls.secretName ))) }}
  USER_TOOLS_TLS_SECRET_NAME: "{{ include "userTools.tlsSecretName" . }}"
  {{- end }}
  USER_TOOLS_VSCODE_ENABLED: "{{ .Values.userToolsOperator.vscode.enabled }}"

  ##
  # Labels
  LABELS_COMMON_APP_RELEASE: {{ .Values.image.tag }}
  LABELS_COMMON_CHART_RELEASE: {{ .Chart.Version }}
