apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kdl-server.server.name" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
  labels:
    {{- include "kdl-server.kdlServerLabels" . | nindent 4 }}
data:
  ##
  # KDL APP configuration
  config.json: |+
    {
      "DESCRIPTION_MIN_WORDS": {{ default "50" .Values.knowledgeGalaxy.config.descriptionMinWords }},
      "KG_SERVER_URL": "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/kg",
      "KNOWLEDGE_GALAXY_ENABLED": {{ .Values.knowledgeGalaxy.enabled }},
      "RELEASE_VERSION": "{{ .Chart.Version }}v{{ .Chart.AppVersion }}",
      "SERVER_NAME": "{{ .Values.global.serverName }}",
      "SERVER_URL": "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}"
    }

  ##
  # Project Operator
  PROJECT_FILEBROWSER_URL: "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/filebrowser/PROJECT_ID/"
  PROJECT_MLFLOW_URL: "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/mlflow/PROJECT_ID/"

  ##
  # User Tools Operator (deprecate)
  USER_TOOLS_VSCODE_URL: "{{ include "http.protocol" . }}://USERNAME-code.{{ .Values.global.domain }}/?folder=/home/coder/repos/REPO_FOLDER"

  ##
  # Knowledge Galaxy
  KNOWLEDGE_GALAXY_URL: "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/kg/projects/PROJECT_ID/"
  KNOWLEDGE_GALAXY_ENABLED: "{{ .Values.knowledgeGalaxy.enabled }}"

  ##
  # Labels
  LABELS_COMMON_APP_RELEASE: {{ .Chart.AppVersion }}
  LABELS_COMMON_CHART_RELEASE: {{ .Chart.Version }}
