{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kdl-server.server.name" . }}
  labels:
    {{- include "kdl-server.kdlServerLabels" . | nindent 4 }}
rules:
  # configmaps and secrets
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    - serviceaccounts
    - pods
    - persistentvolumeclaims
    verbs:
    - '*'
  # CRDs
  - apiGroups:
    - kdl.konstellation.io
    resources:
    - kdlprojects
    - kdlusertools
    verbs:
    - '*'
{{- end }}
