{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kdl-server.server.name" . }}
  labels:
    {{- include "kdl-server.kdlServerLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kdl-server.kdlServerServiceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kdl-server.server.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
