# TODO: only use to keep backward with user-tools
# will be remove and adapt UserTools
apiVersion: v1
kind: Secret
metadata:
  name: kdl-server
  labels:
    app:  kdl-server
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | b64enc }}
  MINIO_ENDPOINT: {{ printf "%s:%s" (default "minio" .Values.env.MINIO_ENDPOINT) (default "9000" .Values.env.MINIO_PORT) | b64enc }}
