apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: 1.0.12
appVersion: undefined.undefined.NaN
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
  - name: enterprise-gateway
    version: "2.5.0"
    repository: "https://charts.spot.io"
