apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: v0.15-rc.3
appVersion: v0.17.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
