apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: v0.15-rc.0
appVersion: v0.15.0
dependencies:
  - name: minio
    version: "8.0.10"
    repository: "https://helm.min.io/"
