apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: v1.0-rc.0
appVersion: kdl-app-v1.1.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
  - name: enterprise-gateway
    version: "2.5.0"
    repository: "https://charts.spot.io"
