domain: kdl.local
tls: 
  enabled: false
ingress:
  type: nginx

kdlServer:
  image:
    repository: konstellation/kdl-server
    tag: latest
    pullPolicy: IfNotPresent

oauth2Proxy:
  image:
    repository: terminus7/oauth2-proxy
    tag: latest
    pullPolicy: IfNotPresent

giteaOauth2Setup:
  image:
    repository: terminus7/gitea-oauth2-setup
    tag: 1.1.5
    pullPolicy: IfNotPresent

mongodb:
  service:
    name: "mongodb"
  auth:
    adminUser: "admin"
    adminPassword: "123456"
  mongodbUsername: "admin"
  mongodbPassword: "123456"
  storage:
    className: standard
    size: 3G
  volumePermissions:
    enabled: false
    image:
      registry: docker.io
      repository: debian
      tag: buster-slim
  initConfigMap:
    name: kdl-mongo-init-script
  persistentVolume:
    enabled: true
    storageClass: standard
    size: 5Gi
