apiVersion: v1
kind: Secret
metadata:
  name: kdl-server
  labels:
    app:  kdl-server
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.rootPassword | b64enc }}
