{{- include "validate.server_environment" . }}

# TODO: only use to keep backward with user-tools
# will be remove and adapt UserTools
apiVersion: v1
kind: Secret
metadata:
  name: kdl-server
  labels:
    app:  kdl-server
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | b64enc }}
  {{- if .Values.env.MINIO_ENDPOINT }}
  MINIO_ENDPOINT: "{{ .Values.env.MINIO_ENDPOINT | printf "%s:9000" | b64enc }}"
  {{- end }}
