{{- range .Values.natsManager.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kai.natsManager.name" $ }}-{{ .name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
  labels:
    {{- include "kai.natsManagerLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{- if regexMatch "\n" $value }}
  {{ $key }}: |
    {{ $value | nindent 4 | trim | b64enc }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{ end }}
