apiVersion: v1
kind: Service
metadata:
  name: {{ include "kai.natsManager.name" . }}
  labels:
    {{- include "kai.natsManagerLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.natsManager.service.port }}
      targetPort: {{ .Values.natsManager.env.KAI_ADMIN_API_PORT | default (.Values.natsManager.service.targetPort | default .Values.natsManager.service.port) }}
      protocol: TCP
      name: grpc
    {{- range $port := .Values.natsManager.service.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "kai.selectorK8sManagerLabels" . | nindent 4 }}
