{{- if .Values.projectOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdl-server.project-operator.name" . }}-metrics
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
