{{- if .Values.projectOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdl-server.project-operator.name" . }}
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
rules:
  # Namespace Management
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

  # Core Resources Management
  - apiGroups: [""]
    resources:
      - secrets
      - persistentvolumeclaims
      - configmaps
      - serviceaccounts
      - services
      - events
      - pods
    verbs: ["*"]

  # Workload Management
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]

  # Network Management
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["*"]

  # Resource Management
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]

  # Security and Availability
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs: ["*"]

  # KDL Project Management
  - apiGroups: ["kdl.konstellation.io"]
    resources:
      - kdlprojects
      - kdlprojects/status
      - kdlprojects/finalizers
    verbs: ["*"]

  # Operator Status Management
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
{{- end }}
