{{- if and .Values.projectOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kdl-server.project-operator.name" . }}
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kdl-server.project-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kdl-server.projectOperatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
