{{- $globalSecrets := .Values.global.imagePullSecrets | default list }}
{{- $localSecrets := .Values.projectOperator.imagePullSecrets | default list }}
{{- $combinedSecrets := concat $globalSecrets $localSecrets }}

{{ if .Values.projectOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kdl-server.project-operator.name" . }}
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.projectOperator.autoscaling.enabled }}
  replicas: {{ .Values.projectOperator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kdl-server.selectorProjectOperatorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.projectOperator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kdl-server.projectOperatorLabels" . | nindent 8 }}
        {{- with .Values.projectOperator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if $combinedSecrets }}
      imagePullSecrets:
        {{- range $combinedSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "kdl-server.projectOperatorServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.projectOperator.podSecurityContext | nindent 8 }}
      {{- with .Values.projectOperator.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: project-operator
          securityContext:
            {{- toYaml .Values.projectOperator.securityContext | nindent 12 }}
          {{- if .Values.global.imageRegistry }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.projectOperator.image.repository }}:{{ .Values.projectOperator.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.projectOperator.image.repository }}:{{ .Values.projectOperator.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.projectOperator.image.pullPolicy }}
          {{- with .Values.projectOperator.command }}
          command: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.projectOperator.args }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.projectOperator.service.targetPort | default .Values.projectOperator.service.port }}
              protocol: TCP
            {{- range $port := .Values.projectOperator.service.extraPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.targetPort }}
              protocol: TCP
            {{- end }}
          lifecycle:
            {{- with .Values.projectOperator.lifecycle }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.knowledgeGalaxy.resources | nindent 12 }}
        {{- if .Values.projectOperator.extraContainers }}
          {{- toYaml .Values.projectOperator.extraContainers | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.projectOperator.terminationGracePeriodSeconds }}
      {{- with .Values.projectOperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.projectOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.projectOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.projectOperator.topologySpreadConstraints }}
      {{- $_ := include "kdl-server.patchTopologySpreadConstraintsProjectOperator" $ }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
