{{- if and .Values.projectOperator.enabled .Values.projectOperator.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kdl-server.fullname" . }}-project-operator
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kdl-server.fullname" . }}
  minReplicas: {{ .Values.projectOperator.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.projectOperator.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.projectOperator.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.projectOperator.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.projectOperator.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.projectOperator.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
