{{- if and .Values.projectOperator.enabled .Values.projectOperator.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kdl-server.fullname" . }}-project-operator
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kdl-server.selectorUserToolsOperatorLabels" . | nindent 6 }}
  {{- if .Values.projectOperator.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.projectOperator.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.projectOperator.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.projectOperator.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
