{{ if and .Values.projectOperator.enabled .Values.projectOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdl-server.projectOperatorServiceAccountName" . }}
  labels:
    {{- include "kdl-server.projectOperatorLabels" . | nindent 4 }}
  {{- with .Values.projectOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.projectOperator.serviceAccount.automount | default "false" }}
{{- end }}
