affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - my-app
        topologyKey: "kubernetes.io/hostname"

nodeSelector:
  nodeLabel: nodeValue

tolerations:
  - key: "nodeLabel"
    operator: "Equal"
    value: "nodeValue"
    effect: "NoSchedule"
