livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true

livenessProbeCustom:
  httpGet:
    path: /healthz
    port: 8080
  failureThreshold: 3
  initialDelaySeconds: 200
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5

readinessProbeCustom:
  httpGet:
    path: /ready
    port: 8080
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

startupProbeCustom:
  httpGet:
    path: /start
    port: 8080
  failureThreshold: 3
  initialDelaySeconds: 200
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
