apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-tpl-configmap
  labels:
    app: kubeconfig-tpl-configmap
data:

  generate-kubeconfig.sh: |+
    #!/bin/sh
    cp /kubeconfig.tpl /home/coder/kubeconfig
    sed -i "s/{CACERT}/$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 | tr -d '\n')/g" /home/coder/kubeconfig
    sed -i "s/{TOKEN}/$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)/g" /home/coder/kubeconfig

  kubeconfig.tpl: |+
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {CACERT}
        server: https://127.0.0.1:6443
      name: konstellation
    contexts:
    - context:
        cluster: konstellation
        user: coder
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: coder
      user:
        token: {TOKEN}
