apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-configmap
  labels:
    app: kubeconfig-configmap
data:

  kubeconfig.tpl: |+
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {CACERT}
        server: https://127.0.0.1:6443
      name: konstellation
    contexts:
    - context:
        cluster: konstellation
        user: coder
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: coder
      user:
        token: {TOKEN}
