apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-tools-{{ .Values.usernameSlug }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-tools-{{ .Values.usernameSlug }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  resourceNames: 
  - usertools-{{ .Values.usernameSlug }}-user-tools-0
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-tools-{{ .Values.usernameSlug }}
subjects:
- kind: ServiceAccount
  name: user-tools-{{ .Values.usernameSlug }}
roleRef:
  kind: Role
  name: user-tools-{{ .Values.usernameSlug }}
  apiGroup: rbac.authorization.k8s.io
