apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vscode-runtime-{{ .Values.usernameSlug }}
    flavorId: 61383716a8c1d7ce4764f411
  name: vscode-runtime-{{ .Values.usernameSlug }}
spec:
  containers:
  - name: {{ .Chart.Name }}-runtime-vscode
    image: {{ .Values.vscodeRuntime.image.repository }}:{{ .Values.vscodeRuntime.image.tag }}
    imagePullPolicy: {{ .Values.vscodeRuntime.image.pullPolicy }}
    command:
      - /bin/bash
      - -c
      - "trap : TERM INT; sleep infinity & wait"
    volumeMounts:
    - name: user-pvc
      mountPath: /home/coder
    {{- if .Values.sharedVolume.name }}
    - name: {{ .Values.sharedVolume.name }}
      mountPath: /home/coder/shared-storage
      readOnly: true
    {{- end }}
    - name: {{ .Values.usernameSlug }}-ssh-keys-vol
      mountPath: /home/coder/.ssh/id_rsa
      subPath: id_rsa
      readOnly: true
  volumes:
    {{ if .Values.sharedVolume.name -}}
    - name: {{ .Values.sharedVolume.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.sharedVolume.name }}-claim
        readOnly: true
    {{- end }}
    - name: {{ .Values.usernameSlug }}-ssh-keys-vol
      secret:
        secretName: {{ .Values.usernameSlug }}-ssh-keys
        items:
        - key: KDL_USER_PRIVATE_SSH_KEY
          path: id_rsa
    - name: user-pvc
      persistentVolumeClaim:
        claimName: user-pvc-usertools-{{ .Values.usernameSlug }}-user-tools-0
