{{- if .Values.k8sManager.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kai.k8sManager.name" . }}
  labels:
    {{- include "kai.k8sManagerLabels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - pods
      - secrets
      - services
      - jobs
      - pods/log
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["*"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["*"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
{{- end }}
