apiVersion: v1
kind: Service
metadata:
  name: {{ include "kai.k8sManager.name" . }}
  labels:
    {{- include "kai.k8sManagerLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.k8sManager.service.port }}
      targetPort: {{ .Values.k8sManager.env.KAI_ADMIN_API_PORT | default (.Values.k8sManager.service.targetPort | default .Values.k8sManager.service.port) }}
      protocol: TCP
      name: grpc
    {{- range $port := .Values.k8sManager.service.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "kai.selectorK8sManagerLabels" . | nindent 4 }}
