{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kdl-server.fullname" . }}-knowledge-galaxy
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
  labels:
    {{- include "kdl-server.knowledgeGalaxyLabels" . | nindent 4 }}
data:
  config.json: |-
    {
      "SERVER_NAME": "{{ .Values.global.serverName }}",
      "SERVER_URL": "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/kg",
      "MODE": "iframe",
      "BASENAME": "/kg/"
    }
{{- end }}
