{{- if and .Values.knowledgeGalaxy.enabled .Values.knowledgeGalaxy.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kdl-server.knowledge-galaxy.name" . }}
  labels:
    {{- include "kdl-server.knowledgeGalaxyLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kdl-server.fullname" . }}
  minReplicas: {{ .Values.knowledgeGalaxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.knowledgeGalaxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.knowledgeGalaxy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.knowledgeGalaxy.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.knowledgeGalaxy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.knowledgeGalaxy.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
