{{- if and .Values.knowledgeGalaxy.enabled .Values.knowledgeGalaxy.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kdl-server.knowledge-galaxy.name" . }}
  labels:
    {{- include "opencti.knowledgeGalaxyLabels" . | nindent 4 }}
spec:
  {{- if and (not .Values.knowledgeGalaxy.networkPolicy.policyTypes) (not .Values.knowledgeGalaxy.networkPolicy.ingress) (not .Values.knowledgeGalaxy.networkPolicy.egress) }}
  podSelector: {}
  {{- else }}
  podSelector:
    matchLabels:
      {{- include "opencti.selectorWorkerLabels" . | nindent 6 }}
  {{- end }}

  {{- if .Values.knowledgeGalaxy.networkPolicy.policyTypes }}
  {{- with .Values.knowledgeGalaxy.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  policyTypes:
    - Ingress
    - Egress
  {{- end }}

  {{- if .Values.knowledgeGalaxy.networkPolicy.ingress }}
  {{- with .Values.knowledgeGalaxy.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  ingress:
  - {}
  {{- end }}

  {{- if .Values.knowledgeGalaxy.networkPolicy.egress }}
  {{- with .Values.knowledgeGalaxy.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  egress:
  - {}
  {{- end }}

{{- end }}
