{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdl-server.knowledge-galaxy.name" . }}
  labels:
    {{- include "kdl-server.knowledgeGalaxyLabels" . | nindent 4 }}
spec:
  type: {{ .Values.knowledgeGalaxy.service.type }}
  ports:
    - port: {{ .Values.knowledgeGalaxy.service.port }}
      targetPort: {{ .Values.knowledgeGalaxy.service.targetPort | default .Values.knowledgeGalaxy.service.port }}
      protocol: TCP
      name: http
      {{- if and (eq "NodePort" .Values.knowledgeGalaxy.service.type) .Values.knowledgeGalaxy.service.nodePort }}
      nodePort: {{ .Values.knowledgeGalaxy.service.nodePort }}
      {{- end }}
    {{- range $port := .Values.knowledgeGalaxy.service.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "kdl-server.selectorKnowledgeGalaxyLabels" . | nindent 4 }}
{{ end }}
