{{ if and .Values.knowledgeGalaxy.enabled .Values.knowledgeGalaxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdl-server.knowledgeGalaxyServiceAccountName" . }}
  labels:
    {{- include "kdl-server.knowledgeGalaxyLabels" . | nindent 4 }}
  {{- with .Values.knowledgeGalaxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.knowledgeGalaxy.serviceAccount.automount | default "false" }}
{{- end }}
