apiVersion: v2
type: application
name: kai
description: A Helm chart to deploy KAI
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://gitlab.intelygenz.com/konstellation-io/kai/kai
maintainers:
  - name: ialejandro
    email: ivan.alejandro@intelygenz.com
  - name: alpiquero
    email: angelluis.piquero@intelygenz.com
keywords:
  - ai
  - kai
  - konstellation
  - kubernetes
  - machine learning
dependencies:
  - name: konstellation-base
    alias: keycloak
    version: "1.1.2"
    repository: oci://ghcr.io/konstellation-io/helm-charts
    condition: keycloak.enabled
  - name: minio
    version: "5.4.0"
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: mongodb
    version: "16.2.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: nats
    version: "1.2.10"
    repository: https://nats-io.github.io/k8s/helm/charts
    condition: nats.enabled
  - name: postgresql
    version: "15.5.38"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "20.7.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: vault
    version: "0.29.1"
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
