apiVersion: v2
type: application
name: kai
description: A Helm chart to deploy KAI
version: 0.2.0
appVersion: "0.3.0-develop.17"
sources:
  - https://gitlab.intelygenz.com/konstellation-io/kai/kai
maintainers:
  - name: ialejandro
    email: ivan.alejandro@intelygenz.com
  - name: alpiquero
    email: angelluis.piquero@intelygenz.com
keywords:
  - ai
  - kai
  - konstellation
  - kubernetes
  - machine learning
dependencies:
  - name: minio
    version: "5.0.14"
    repository: https://charts.min.io/
  - name: grafana
    version: "7.0.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki
    repository: "https://grafana.github.io/helm-charts"
    version: "5.36.3"
    condition: loki.enabled
  - name: prometheus
    version: "25.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: redis
    version: "18.2.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: nats
    version: "1.1.9"
    repository: "https://nats-io.github.io/k8s/helm/charts"
    condition: nats.enabled
