{{ if .Values.userToolsOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdl-server.user-tools-operator.name" . }}
  labels:
    {{- include "kdl-server.userToolsOperatorLabels" . | nindent 4 }}
rules:
# Core API permissions for basic resources
- apiGroups:
  - ""
  resources:
  - secrets
  - persistentvolumeclaims
  - configmaps
  - serviceaccounts
  - services
  - events
  verbs:
  - '*'

# KDLUserTools custom resource permissions
- apiGroups:
  - kdl.konstellation.io
  resources:
  - kdlusertools
  - kdlusertools/status
  - kdlusertools/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Workload permissions
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'

# Network-related permissions
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - '*'

# Autoscaling permissions
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'

# Pod Disruption Budget permissions
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'

# Pod Security Context permissions for security configurations
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
