{{- if .Values.userToolsOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdl-server.user-tools-operator.name" . }}
  labels:
    {{- include "kdl-server.userToolsOperatorLabels" . | nindent 4 }}
rules:
# Namespace
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

# Core
- apiGroups: [""]
  resources:
  - secrets
  - persistentvolumeclaims
  - configmaps
  - serviceaccounts
  - services
  - events
  verbs: ["*"]

# Roles
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - roles
  - rolebindings
  verbs: ["*"]

# Workload
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["*"]

# Network
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  - networkpolicies
  verbs: ["*"]

# Resource
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]

# Security and availability
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs: ["*"]

# KDL UserTools operator
- apiGroups: ["kdl.konstellation.io"]
  resources:
  - kdlusertools
  - kdlusertools/status
  - kdlusertools/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# KDL UserTools
- apiGroups: ["kdl.konstellation.io"]
  resources:
  - kdlusertools
  - kdlusertools/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
