{{ if .Values.userToolsOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kdl-server.user-tools-operator.name" . }}
  labels:
    {{- include "kdl-server.userToolsOperatorLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kdl-server.userToolsOperatorServiceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kdl-server.user-tools-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
