{{- if .Values.userToolsOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kdl-server.user-tools-operator.name" . }}-leader-election
  labels:
    {{- include "kdl-server.userToolsOperatorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kdl-server.user-tools-operator.name" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "kdl-server.userToolsOperatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
