{{ if and .Values.userToolsOperator.enabled .Values.userToolsOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdl-server.userToolsOperatorServiceAccountName" . }}
  labels:
    {{- include "kdl-server.userToolsOperatorLabels" . | nindent 4 }}
  {{- with .Values.userToolsOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.userToolsOperator.serviceAccount.automount | default "false" }}
{{- end }}
