{{ if and .Values.userToolsOperator.enabled .Values.userToolsOperator.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kdl-server.user-tools-operator.name" . }}
  labels:
    {{- include "kdl-server.userToolsOperatorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kdl-server.selectorUserToolsOperatorLabels" . | nindent 8 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.userToolsOperator.serviceMonitor.interval | quote }}
    scrapeTimeout: {{ .Values.userToolsOperator.serviceMonitor.scrapeTimeout | quote }}
    {{- if .Values.userToolsOperator.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.userToolsOperator.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.userToolsOperator.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml .Values.userToolsOperator.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
{{- end }}
