name: "[Helm Charts] Releases"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**/*.yaml'
      - 'charts/**/*.yml'
      - 'charts/**/*.tpl'
      - 'charts/**/*.txt'
      - '!charts/**/examples/*.yaml'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # default install latest (stable)
      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
              helm dependency list $dir 2> /dev/null | \
              grep -v 'oci://' | \
              tail +2 | \
              head -n -1 | \
              awk '{ print $1 " " $3 }' | \
              while read -r repo url; do
                  if ! helm repo list | grep -q "^${repo}[[:space:]]"; then
                      helm repo add "$repo" "$url"
                  fi
              done
          done

      # See https://github.com/helm/chart-releaser#config-file
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.PAT }}
          CR_SKIP_EXISTING: true
          CR_GENERATE_RELEASE_NOTES: true

      - name: Login in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install Oras
        uses: oras-project/setup-oras@v1

      # ref: https://github.com/backstage/charts/blob/88240ce7a0726e3773ee0e4866fbe6325c15267b/.github/workflows/release.yml#L50
      - name: Publish and Sign OCI Charts
        run: |
          for chart in `find .cr-release-packages -name '*.tgz' -print`; do
            helm push ${chart} oci://ghcr.io/${GITHUB_REPOSITORY} |& tee helm-push-output.log
            file_name=${chart##*/}
            chart_name=${file_name%-[0-9]*}
            digest=$(awk -F "[, ]+" '/Digest/{print $NF}' < helm-push-output.log)
            cosign sign -y "ghcr.io/${GITHUB_REPOSITORY}/${chart_name}@${digest}"

            oras push "ghcr.io/${GITHUB_REPOSITORY}/${chart_name}:"
          done
        env:
          COSIGN_EXPERIMENTAL: 1
