name: "[Helm Charts] Lint and test PR"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # default install latest (stable)
      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yml)
          if [[ -n "${changed}" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | grep -v 'oci://' | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run ct lint
        if: steps.list-changed.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: ct lint --config .github/ct.yml --lint-conf .github/helmlintconf.yaml

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: helm/kind-action@v1

      - name: Run ct install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config .github/ct.yml --helm-extra-args '--timeout 900s --debug'

      - name: (workflow_dispatch) Run ct install
        if: github.event_name == 'workflow_dispatch'
        run: ct install --config .github/ct.yml --helm-extra-args '--timeout 900s --debug' --all
