name: "[Helm] Check KDL Server new releases"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day

jobs:
  check-and-update-kdl-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get current release
        id: current_release
        run: |
          current_release=$(grep appVersion charts/kdl-server/Chart.yaml | awk '{ print $2 }')
          echo "current_release=$current_release" >> $GITHUB_OUTPUT

      - name: Install updatecli
        uses: updatecli/updatecli-action@v2

      - name: Update dependencies
        run: |
          updatecli apply --config .github/updatecli/helm-kdl-server-appversion.yaml --commit=false

      - name: Get latest release
        id: latest_release
        run: |
          latest_release=$(grep appVersion charts/kdl-server/Chart.yaml | awk '{ print $2 }')
          echo "latest_release=$latest_release" >> $GITHUB_OUTPUT

      - name: Check if release changed
        id: check_changes
        run: |
          if [ ${{ steps.latest_release.outputs.latest_release }} != ${{ steps.current_release.outputs.current_release }} ]; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Update README.md Helm Chart
        if: steps.check_changes.outputs.release_changed == 'true'
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts/kdl-server

      - name: Create PR with changes
        if: steps.check_changes.outputs.release_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "fix: update KDL Server version to ${{ steps.latest_release.outputs.latest_release }}"
          signoff: false
          branch: chore/upgrade-kdl-server-appversion-${{ steps.latest_release.outputs.latest_release }}
          delete-branch: true
          title: '[kdl-server] new release: ${{ steps.latest_release.outputs.latest_release }}'
          body: |
            KDL Server version:
            - :information_source: Current: `${{ steps.current_release.outputs.current_release }}`
            - :up: Upgrade: `${{ steps.latest_release.outputs.latest_release }}`

            Changelog: https://github.com/konstellation-io/kdl-server/releases/tag/${{ steps.latest_release.outputs.latest_release }}
          labels: |
            auto-pr-bump-version
